Add scanner-build image
stackrox/rox-ci-image pull request #129
Opened 2022-05-13 16:07 UTC by RTann

Based on https://github.com/stackrox/rox-ci-image/blob/master/images/stackrox-build.Dockerfile and https://github.com/stackrox/scanner/blob/2.24.0/build/Dockerfile

2022-05-13 17:16 UTC, RTann commented
Not necessary anymore

2022-05-13 18:10 UTC, RTann commented
@gavin-stackrox do you know how to retag the image as `quay.io/stackrox-io/...`? I don't see where that is done for `stackrox-build`

2022-05-13 18:23 UTC, gavin-stackrox commented
> @gavin-stackrox do you know how to retag the image as `quay.io/stackrox-io/...`? I don't see where that is done for `stackrox-build`

Looks like that was quietly missed on the original PR and does not cause a failure:
https://app.circleci.com/pipelines/github/stackrox/rox-ci-image/919/workflows/571d5345-62ba-4271-88f1-1a84ffccd6e5/jobs/6331?invite=true#step-103-2233

I think:
`docker tag "${IMAGE}" "quay.io/stackrox-io/apollo-ci:${TAG}"`
will do it.

2022-05-13 18:25 UTC, RTann commented
ah ok that makes more sense. I could not find that line at all before

2022-05-13 21:30 UTC, gavin-stackrox approved these changes
LGTM assuming it passes scanner CI. I think you can ignore the image scan failures on the other images as you are not proposing to update those anywhere. Or you could check the vulns and snooze them on:
https://docs.engineering.redhat.com/display/StackRox/StackRox+instance+for+CI?src=contextnavpagetreemode

2022-05-13 21:30 UTC, gavin-stackrox commented on .circleci/config.yml
> +    - build-and-push-scanner-build:
This should be added as a required job for `create-or-update-scanner-repo-pr`

2022-05-13 23:48 UTC, RTann commented
> LGTM assuming it passes scanner CI. I think you can ignore the image scan failures on the other images as you are not proposing to update those anywhere. Or you could check the vulns and snooze them on: https://docs.engineering.redhat.com/display/StackRox/StackRox+instance+for+CI?src=contextnavpagetreemode

yep Scanner passes: https://github.com/stackrox/scanner/pull/731

2022-05-16 09:17 UTC, vikin91 requested changes
Almost there - I think, the if-clause needs to be fixed.

2022-05-16 09:17 UTC, vikin91 commented on .circleci/config.yml
> +                    "$flavor" == "scanner-build" ]] && [[ "<< parameters.repo >>" == "scanner" ]]; then
There is something wrong here - this cannot be true.

Did you mean this maybe?

```suggestion
              if [[ ("$flavor" == "stackrox-build" && "<< parameters.repo >>" == "stackrox") ||
                    ("$flavor" == "scanner-build" && "<< parameters.repo >>" == "scanner") ]]; then
```

2022-05-16 16:42 UTC, vikin91 approved these changes
The code looks good now :) 

Could you please check what are the red crosses in the CI?
Edit: Seem to be vulnerabilities only

2022-05-16 17:23 UTC, merged