Add postgres client
stackrox/rox-ci-image pull request #133
Opened 2022-05-25 03:53 UTC by c-du

2022-05-25 17:06 UTC, gavin-stackrox commented
CC @RTann IIRC the reason pg12 is in this image is for stackrox/scanner?

2022-05-25 17:27 UTC, RTann commented
Yeah, Scanner is using PG 12, so we may need a separate testing image for Scanner

2022-05-25 22:08 UTC, c-du commented
> Yeah, Scanner is using PG 12, so we may need a separate testing image for Scanner

Yes, looks like we have to.

2022-05-26 18:20 UTC, gavin-stackrox requested changes
I think @RTann will need to approve based on scanner CI and if that is good enough for scanners need for pg12?

2022-05-26 18:20 UTC, gavin-stackrox commented on images/stackrox-test.Dockerfile
> +        lz4 \
nit: the other packages are sorted alphabetically. Can this be moved after `lsof`?

2022-05-27 18:24 UTC, gavin-stackrox approved these changes

2022-05-27 19:15 UTC, merged