Upgrade Go to 1.18.4
stackrox/rox-ci-image pull request #164
Opened 2022-08-29 20:32 UTC by misberner

2022-08-29 20:35 UTC, connorgorman commented on images/stackrox-build.Dockerfile
> +    dnf -y groupinstall "Developmengt Tools" && \
wrong spelling?

2022-08-29 20:35 UTC, connorgorman requested changes
1.18.4 is the highest version downstream

2022-08-29 20:37 UTC, misberner commented on images/stackrox-build.Dockerfile
> +    dnf -y groupinstall "Developmengt Tools" && \
lol, no idea what happened there. reverted

2022-08-29 20:43 UTC, misberner commented
Ah, good catch. Downgraded

2022-08-29 21:26 UTC, connorgorman approved these changes
lg thx

2022-08-30 05:55 UTC, rukletsov approved these changes

2022-09-01 19:17 UTC, merged